/*// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmuKDDdAYU0Gxem8adEGCK10u7PLkov8',
    appId: '1:998148765721:web:a9b926f290c4f3ae235288',
    messagingSenderId: '998148765721',
    projectId: 'cup-du-mande',
    authDomain: 'cup-du-mande.firebaseapp.com',
    storageBucket: 'cup-du-mande.appspot.com',
    measurementId: 'G-28269PZHKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5s3cyJyD74EivdFkqnUtSRSKB0Ma6QE',
    appId: '1:998148765721:android:3e66a583dd5724c3235288',
    messagingSenderId: '998148765721',
    projectId: 'cup-du-mande',
    storageBucket: 'cup-du-mande.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN7rGR7FTDz6AWy967tXWhGGGAZrm6HOE',
    appId: '1:998148765721:ios:92a2f018b6d81528235288',
    messagingSenderId: '998148765721',
    projectId: 'cup-du-mande',
    storageBucket: 'cup-du-mande.appspot.com',
    iosClientId: '998148765721-a05kjbt5a5tccn1sv49bupc6j3e8n2ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.projet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN7rGR7FTDz6AWy967tXWhGGGAZrm6HOE',
    appId: '1:998148765721:ios:92a2f018b6d81528235288',
    messagingSenderId: '998148765721',
    projectId: 'cup-du-mande',
    storageBucket: 'cup-du-mande.appspot.com',
    iosClientId: '998148765721-a05kjbt5a5tccn1sv49bupc6j3e8n2ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.projet1',
  );
}*/
